# Generated by Django 2.2.5 on 2019-10-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=500)),
                ('category_image', models.ImageField(default='', upload_to='media/category')),
                ('category_status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TableRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ip_address', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('dateandtime_rating', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TableWallpaperUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='media/wallpaper/None/no-img.jpg', upload_to='media/wallpapers/')),
                ('category_id', models.IntegerField()),
                ('image_date', models.DateTimeField()),
                ('wallpaper_tags', models.CharField(max_length=500)),
                ('total_rating', models.CharField(max_length=500)),
                ('wallpaper_rating_average', models.CharField(max_length=500)),
                ('wallpaper_total_views', models.IntegerField()),
                ('wallpaper_total_downloads', models.IntegerField()),
            ],
        ),
    ]
