# Generated by Django 2.2.5 on 2019-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablewallpaperupload',
            name='thumbnail',
            field=models.ImageField(default='media/wallpaper/None/no-img.jpg', editable=False, upload_to='media/thumbs/'),
        ),
    ]
