# Generated by Django 2.2.5 on 2019-10-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperapi', '0002_tablewallpaperupload_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablewallpaperupload',
            name='thumbnail',
            field=models.ImageField(default='media/wallpaper/None/no-img.jpg', upload_to='media/thumbs/'),
        ),
    ]
